return {
    Update_New_Frame = true,
    Update_New_ViewportFrame = true,
    Update_New_ScrollingFrame = true,
    Update_New_TextLabel = true,
    Update_New_TextButton = true,
    Update_New_TextBox = true,
    Update_New_ImageLabel = true,
    Update_New_ImageButton = true,
    Update_New_ScreenGui = true,
    Update_New_SurfaceGui = true,
    Update_New_BillBoardGui = true,
    Update_New_UICorner = true,
    Update_New_UIGridLayout = true,
    Update_New_UIListLayout = true,
    Update_New_UIGradient = true,
    Update_New_UITableLayout = true,
    Update_New_UISizeConstraint = true,
    Update_New_UITextSizeConstraint = true,
    Update_New_UIPageLayout = true,
    Update_New_UIAspectRationConstraint = true,
    Update_New_UIPadding = true,
    Update_New_UIScale = true,
    Update_New_UIStroke = true,
}