return {
    {Name = "Update_New_Frame", Value = true},
    {Name = "Update_New_ViewportFrame", Value = true},
    {Name = "Update_New_ScrollingFrame", Value = true},
    {Name = "Update_New_TextLabel", Value = true},
    {Name = "Update_New_TextButton", Value = true},
    {Name = "Update_New_TextBox", Value = true},
    {Name = "Update_New_ImageLabel", Value = true},
    {Name = "Update_New_ImageButton", Value = true},
    {Name = "Update_New_ScreenGui", Value = true},
    {Name = "Update_New_SurfaceGui", Value = true},
    {Name = "Update_New_BillBoardGui", Value = true},
    {Name = "Update_New_UICorner", Value = true},
    {Name = "Update_New_UIGridLayout", Value = true},
    {Name = "Update_New_UIListLayout", Value = true},
    {Name = "Update_New_UIGradient", Value = true},
    {Name = "Update_New_UITableLayout", Value = true},
    {Name = "Update_New_UISizeConstraint", Value = true},
    {Name = "Update_New_UITextSizeConstraint", Value = true},
    {Name = "Update_New_UIPageLayout", Value = true},
    {Name = "Update_New_UIAspectRationConstraint", Value = true},
    {Name = "Update_New_UIPadding", Value = true},
    {Name = "Update_New_UIScale", Value = true},
    {Name = "Update_New_UIStroke", Value = true},
}